name: Python CI/CD

# Trigger the workflow on push and pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # The machine on which to run the job (Ubuntu in this case)

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # This step checks out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2  # This sets up the Python environment
      with:
        python-version: '3.8'  # Specify the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrading pip
        pip install -r requirements.txt || echo "No requirements.txt found"  # Installing dependencies (if any)

    - name: Run Python script
      run: python helloworld.py  # Run the Python script

